<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Worker;
use Illuminate\Support\Facades\DB;

class ProperWorkerSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::statement('TRUNCATE TABLE workers');
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $workers = [
            [
                'public_id' => 'WRK0001',
                'agency_id' => 1,
                'category_id' => 1,
                'location_id' => 7,
                'name' => 'Siti Demina',
                'gender' => 'female',
                'birth_date' => '2001-03-15',
                'photo_path' => 'https://randomuser.me/api/portraits/women/65.jpg',
                'bio' => 'Pengalaman 3 tahun sebagai pembantu rumah tangga. Terampil dalam memasak masakan Indonesia dan membersihkan rumah. Ramah dan dapat diandalkan.',
                'phone' => '081234567891',
                'verification_status' => 'verified',
                'verified_at' => '2025-08-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 3,
                'availability_status' => 'available',
                'rating' => 4.50,
                'total_reviews' => 12,
                'total_completed_orders' => 28,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0002',
                'agency_id' => 2,
                'category_id' => 5,
                'location_id' => 5,
                'name' => 'Ahmad Fadli Rahman',
                'gender' => 'male',
                'birth_date' => '2000-07-22',
                'photo_path' => 'https://randomuser.me/api/portraits/men/41.jpg',
                'bio' => 'Supir berpengalaman 4 tahun, menguasai area Jabodetabek. Bersih dan rapi dalam menjaga kendaraan. Memiliki SIM A aktif.',
                'phone' => '082345678902',
                'verification_status' => 'verified',
                'verified_at' => '2025-06-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 4,
                'availability_status' => 'available',
                'rating' => 4.80,
                'total_reviews' => 18,
                'total_completed_orders' => 45,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0003',
                'agency_id' => 2,
                'category_id' => 2,
                'location_id' => 6,
                'name' => 'Dewi Lestari',
                'gender' => 'female',
                'birth_date' => '2002-11-08',
                'photo_path' => 'https://randomuser.me/api/portraits/women/32.jpg',
                'bio' => 'Baby sitter profesional, pengalaman merawat anak usia 0-5 tahun. Sabar dan telaten dalam mengurus anak. Bersertifikat first aid.',
                'phone' => '083456789013',
                'verification_status' => 'verified',
                'verified_at' => '2025-10-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 2,
                'availability_status' => 'available',
                'rating' => 4.90,
                'total_reviews' => 25,
                'total_completed_orders' => 38,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0004',
                'agency_id' => 1,
                'category_id' => 4,
                'location_id' => 3,
                'name' => 'Mahesa Wibowo',
                'gender' => 'male',
                'birth_date' => '2001-09-30',
                'photo_path' => 'https://randomuser.me/api/portraits/men/68.jpg',
                'bio' => 'Tukang kebun profesional, ahli dalam merawat tanaman hias dan sayuran. Pengalaman 5 tahun di berbagai perumahan.',
                'phone' => '084567890124',
                'verification_status' => 'verified',
                'verified_at' => '2025-04-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 5,
                'availability_status' => 'available',
                'rating' => 4.60,
                'total_reviews' => 15,
                'total_completed_orders' => 32,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0005',
                'agency_id' => 2,
                'category_id' => 3,
                'location_id' => 1,
                'name' => 'Rina Amelia',
                'gender' => 'female',
                'birth_date' => '2002-04-18',
                'photo_path' => 'https://randomuser.me/api/portraits/women/44.jpg',
                'bio' => 'Pengalaman 2 tahun sebagai pembantu rumah tangga dan baby sitter. Multitalent, dapat memasak, membersihkan, dan merawat anak.',
                'phone' => '085678901235',
                'verification_status' => 'verified',
                'verified_at' => '2025-11-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 2,
                'availability_status' => 'available',
                'rating' => 4.30,
                'total_reviews' => 8,
                'total_completed_orders' => 19,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0006',
                'agency_id' => 1,
                'category_id' => 4,
                'location_id' => 1,
                'name' => 'Muhammad Rizki',
                'gender' => 'male',
                'birth_date' => '2000-12-25',
                'photo_path' => 'https://randomuser.me/api/portraits/men/32.jpg',
                'bio' => 'Tukang kebun dengan pengalaman 6 tahun. Mengenal baik semua urusan tanaman bunga dan tanaman hias. Disiplin dan dapat dipercaya.',
                'phone' => '086789012346',
                'verification_status' => 'verified',
                'verified_at' => '2025-02-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 6,
                'availability_status' => 'available',
                'rating' => 4.70,
                'total_reviews' => 22,
                'total_completed_orders' => 56,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0007',
                'agency_id' => 2,
                'category_id' => 1,
                'location_id' => 10,
                'name' => 'Fitri Handayani',
                'gender' => 'female',
                'birth_date' => '2003-01-12',
                'photo_path' => 'https://randomuser.me/api/portraits/women/28.jpg',
                'bio' => 'Pembantu rumah tangga muda yang energik dan cepat belajar. Terampil dalam memasak masakan tradisional dan modern.',
                'phone' => '087890123457',
                'verification_status' => 'verified',
                'verified_at' => '2025-12-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 1,
                'availability_status' => 'available',
                'rating' => 4.20,
                'total_reviews' => 6,
                'total_completed_orders' => 12,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0008',
                'agency_id' => 1,
                'category_id' => 4,
                'location_id' => 8,
                'name' => 'Andi Wijaya',
                'gender' => 'male',
                'birth_date' => '2001-06-14',
                'photo_path' => 'https://randomuser.me/api/portraits/men/75.jpg',
                'bio' => 'Tukang kebun dan maintenance rumah. Pengalaman 4 tahun dalam perawatan taman dan perbaikan kecil rumah tangga.',
                'phone' => '088901234568',
                'verification_status' => 'verified',
                'verified_at' => '2025-09-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 4,
                'availability_status' => 'available',
                'rating' => 4.40,
                'total_reviews' => 11,
                'total_completed_orders' => 26,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0009',
                'agency_id' => 2,
                'category_id' => 2,
                'location_id' => 9,
                'name' => 'Sri Wahyuni',
                'gender' => 'female',
                'birth_date' => '2002-08-07',
                'photo_path' => 'https://randomuser.me/api/portraits/women/52.jpg',
                'bio' => 'Baby sitter senior dengan pengalaman 7 tahun. Ahli dalam mengurus anak berkebutuhan khusus dan mengajar anak usia dini.',
                'phone' => '089012345679',
                'verification_status' => 'verified',
                'verified_at' => '2024-11-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 7,
                'availability_status' => 'available',
                'rating' => 4.90,
                'total_reviews' => 35,
                'total_completed_orders' => 72,
                'is_available' => 1,
                'is_active' => 1,
            ],
            [
                'public_id' => 'WRK0010',
                'agency_id' => 1,
                'category_id' => 5,
                'location_id' => 5,
                'name' => 'Eko Prasetyo',
                'gender' => 'male',
                'birth_date' => '2000-10-19',
                'photo_path' => 'https://randomuser.me/api/portraits/men/47.jpg',
                'bio' => 'Supir dan helper rumah tangga. Pengalaman 3 tahun, dapat mengemudikan mobil manual dan matic. Bantu pekerjaan rumah lainnya.',
                'phone' => '089123456780',
                'verification_status' => 'verified',
                'verified_at' => '2025-07-19 15:40:41',
                'rejection_reason' => null,
                'experience_years' => 3,
                'availability_status' => 'available',
                'rating' => 4.10,
                'total_reviews' => 9,
                'total_completed_orders' => 21,
                'is_available' => 1,
                'is_active' => 1,
            ],
        ];

        foreach ($workers as $worker) {
            Worker::create($worker);
        }
    }
}
